name: madmom
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  - cython>=0.25
  - numpy
  - scipy
  - opencv
  - portaudio
  - pyfftw
  - ffmpeg
  - pyaudio
  - pip
  - pip:
    - mido>=1.2.6
    - flake8<4
    - coverage
    - pytest
    - pytest-cov
    - pytest-flake8
    - black
    - pre-commit
    - prospector
