[build-system]
requires = [
    "setuptools",
    "wheel",
    "cython>=0.25",
    "numpy>=1.13.4;python_version!='3.5'",
    "numpy>=1.13.4,<=1.15.2;python_version=='3.5'"
]
build-backend = "setuptools.build_meta"
